modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Evoslab/Breadcrumbs/issues"
[[mods]]
modId="breadcrumbs"
version="1.1.2"
displayName="Breadcrumbs"
logoFile="breadcrumbs.png"
credits="Evo, Nuxthefox, EltrutLikes, AvocadoSpud"
authors="Evo's Lab"
description='''
Blocks and bricks for your bread!
'''

[[dependencies.breadcrumbs]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.breadcrumbs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.breadcrumbs]]
 modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"

