modLoader="javafml" #mandatory

loaderVersion="[35,)"

license="All rights reserved"

issueTrackerURL="https://github.com/Evoslab/Breadcrumbs/issues"

[[mods]] #mandatory

modId="breadcrumbs" #mandatory

version="1.1.0" #mandatory

displayName="Breadcrumbs" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="breadcrumbs.png" #optional

credits=""

authors=""

description='''

'''

[[dependencies.breadcrumbs]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.breadcrumbs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.breadcrumbs]]
 modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"

